eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.13:8761/eureka/
management:
  security:
    enabled: false
server:
  port: 8762
logging:
  file: logs/eureka-client-one.log
spring:
  application:
    name: eureka-client-one